### ISSUE TITLE
Folders can contain dots

### ISSUE THREAD

**Issue by cevek** [Zoltu/typescript-transformer-append-js-extension#1]

**Comment by MicahZoltu** [comment]
Are you running into this issue with a real project, or is it just a hypothetical?  I am aware that there are a bunch of edge cases with my naive file path parsing and I wanted to wait to address them until someone _actually_ ran into them in a real project.

For example, filenames can have `.` in them as well, and a something like `./foo.bar` would be really difficult to determine whether `.bar` was just part of the file name or was an extension without resorting to actually looking up each file on disk (which I would prefer to avoid).

**Comment by cevek** [comment]
I think there is should be tradeoff 
folders which has dots in names have more сhances to occur than files without extension

**Comment by cevek** [comment]
I check my files on projects. I also have imports like `import "./foo.spec"`
I think you should refactor you naive implementation to more aggressive checking that import is ts file

**Comment by MicahZoltu** [comment]
Checking to see if a TS file with matching name exists on disk would require calling into the OS.  TypeScript appears to go through some lengths to avoid directly calling native methods (like file existence checks).  Also, checking for file existence in NodeJS is kind of horrible, with the only way to do so being to try reading a file and catching the exception, which means the library would have to do something lame like using exceptions for flow control (which drives me nuts).  All in all, checking for existence is out of scope for this package since it is intended to be a temporary measure until TypeScript addresses the issue natively.

That being said, I'm going to leave this open for now (and maybe even address some of it) since there are some improvements that can be made without going to disk, like allowing for `.` in folder names.
