### ISSUE TITLE
What about directories?

### ISSUE THREAD

**Issue by VityaSchel** [Zoltu/typescript-transformer-append-js-extension#17]
If I try to import `index` from directory like this:
```js
import foo from './bar/' // bar is a directory with index.ts in it
```
it breaks and outputs
```js
import foo from '/bar/.js'
```

**Comment by MicahZoltu** [comment]
You should not be doing directory imports if you want your project to be ES Module compatible.  While NodeJS will "figure it out", ES Modules need an explicit single file that is pointed to in order to work.

That being said, even though your syntax won't work it *does* seem incorrect that the transformer applies the `.js` suffix after a trailing `/`.

Can you think of a legitimate reason why you would want to include a trailing slash in a project that uses this transformer, given that trailing slashes don't work with ES modules?

**Comment by GervinFung** [comment]
> If I try to import `index` from directory like this:
> 
> ```js
> import foo from './bar/' // bar is a directory with index.ts in it
> ```
> 
> it breaks and outputs
> 
> ```js
> import foo from '/bar/.js'
> ```

Hi, you can give [ts-add-js-extension](https://www.npmjs.com/package/ts-add-js-extension) a try, I also need some user feedbacks as well as I had not try it on large projects.

It does the same thing except that it is not a typescript plugin, it modifies the import/export path of transpiled JavaScript file (it also work with pure JavaScript file if developers are lazy to add the extensions themselves, but I doubt that's the case), it also attempt to resolves `import foo from './bar'` to `import foo from './bar/index.js`. Any feedbacks are welcome

**Comment by MicahZoltu** [comment]
I haven't heard back from @VityaSchel on this so I'm going to assume they resolved their issue another way or stopped using directory imports per suggestion.  If someone can come up with a legitimate use case for folder loading of ES modules, given that they aren't valid outside of NodeJS, I'm willing to re-open this.
